version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on host to 8000 in container
    volumes:
      - .:/app
    environment:
      - PORT=8000
    command: npm run dev
    container_name: industries-dashboard-api